language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
script: ./example/manage.py test authority
env:
  - TRAVIS_DJANGO_VERSION=1.3
  - TRAVIS_DJANGO_VERSION=1.4
  - TRAVIS_DJANGO_VERSION=1.5
  - TRAVIS_DJANGO_VERSION=1.6
  - TRAVIS_DJANGO_VERSION=1.7
install:
  - pip install django==$TRAVIS_DJANGO_VERSION --use-mirrors
matrix:
  exclude:
    - python: "3.3"
      env: TRAVIS_DJANGO_VERSION=1.3
    - python: "3.3"
      env: TRAVIS_DJANGO_VERSION=1.4
notifications:
  email:
    - jason.louard.ward@gmail.com
