language: python
python:
  - "2.7"
env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py33-django18
install:
  - pip install tox
notifications:
  email:
    - jason.louard.ward@gmail.com
script: tox -e $TOX_ENV
